=== tanmay-kapoor/CollegeStuff/WTL/lab2_xml/WTL06.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="books">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="book"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
<xsd:element name="book">
	<xsd:complexType>
		<xsd:sequence>
			 <xsd:element name="title" type="xsd:string" />
			 <xsd:element name="category" type="xsd:string" />
			 <xsd:element name="author" type="xsd:string" />
			 <xsd:element name="publisher" type="xsd:string" />
			 <xsd:element name="year" type="xsd:positiveInteger" />
			 <xsd:element name="isbn" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tanmay-kapoor/CollegeStuff/WTL/lab2_xml/WTL06.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href=" WTL06.xslt" ?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WTL06.xsd">
  <book>
    <title>Movie 1</title>
    <category>Avengers</category>
    <author>10-01-2020</author>
    <publisher>Action</publisher>
    <year>2000</year>
    <isbn>35</isbn>
  </book>
  <book>
    <title>Movie 2</title>
    <category>Fast and Furious</category>
    <author>5-10-2017</author>
    <publisher>Racing</publisher>
    <year>1989</year>
    <isbn>38</isbn>
  </book>
  <book>
    <title>Movie 3</title>
    <category>Train to Busan</category>
    <author>21-08-2019</author>
    <publisher>Horror</publisher>
    <year>2020</year>
    <isbn>39</isbn>
  </book>
  <book>
    <title>Movie 4</title>
    <category>Rowdy Rathore</category>
    <author>10-04-2015</author>
    <publisher>Action</publisher>
    <year>2000</year>
    <isbn>50</isbn>
  </book>
</books>
